#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Anisha Gunjal
url: 'anisha2102.github.io'
baseurl: '' #change it according to your repository name
description: Anisha Gunjal's personal webpage
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: berry # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-83979019-1

plugins: ['jekyll/scholar']

# Custom vars
scholar:
  style: bib.csl
  locale: en

  sort_by: year, month
  order: descending
  group_order: descending

  source: ./_bibliography
  bibliography: publications.bib
  bibliography_template: bib

  bibliography_list_tag: 'div'
  bibliography_item_tag: 'span'

  bibliography_list_attributes:
    reversed: "reversed"

  replace_strings: true
  join_strings:    true

  bibtex_skip_fields: ['abstract', 'code', 'data', 'month_numeric', 'project', 'tool', 'results']

  repository: materials

  #details_dir:    bibliography
  #details_layout: bibtex.html
  #details_link:   Details

  query: "@*"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
